DIR_MODULE_DISPLAY		:= display
DIR_INTERFACE_DISPLAY	:= $(DIR_MODULE_DISPLAY)
DIR_INTERNAL_DISPLAY	:= $(DIR_MODULE_DISPLAY)/_internal

SRC_INTERFACE_DISPLAY	:= 
SRC_INTERNAL_DISPLAY	:= 

OBJ_DISPLAY			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_DISPLAY)/, $(SRC_INTERFACE_DISPLAY:.c=.o))
OBJ_DISPLAY			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_DISPLAY)/, $(SRC_INTERNAL_DISPLAY:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_DISPLAY)/%.o: $(DIR_SRC)/$(DIR_MODULE_DISPLAY)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_DISPLAY)/_internal -c $< -o $@
