DIR_MODULE_READER		:= reader
DIR_INTERFACE_READER	:= $(DIR_MODULE_READER)
DIR_INTERNAL_READER	:= $(DIR_MODULE_READER)/_internal

SRC_INTERFACE_READER	:= reader.c 
SRC_INTERNAL_READER	:= _bmp.c _write.c 

OBJ_READER			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_READER)/, $(SRC_INTERFACE_READER:.c=.o))
OBJ_READER			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_READER)/, $(SRC_INTERNAL_READER:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_READER)/%.o: $(DIR_SRC)/$(DIR_MODULE_READER)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_READER)/_internal -c $< -o $@
